### ISSUE TITLE
Name 'Preprocessing' is not defined in /yann/utils/datasets.py

### ISSUE THREAD

**Issue by JordanRushing** [ragavvenkatesan/yann#16]
While embarking through your quick-start documentation for YANN I encountered an issue with datasets.py when cooking the MNIST data from Skdata. 

Attached is a screenshot featuring a python interpreter and the associated behavior of the cook_mnist() function included in datasets.py where the name 'preprocessing' appears undefined:

![cook_mnist_issue](https://cloud.githubusercontent.com/assets/3335605/23110661/a21725ea-f6e8-11e6-83cb-e45087818786.png)

To note - the 'preprocessing' name is mentioned in a comment at the beginning of datasets.py

**Comment by ragavvenkatesan** [comment]
The preprocessing method is moved to yann.utils.image I think. I must have added a 
`from yann.utils.image import preprocessing` at the beginning of `dataset.py`.  I wonder where it went. I will add it (if missing) in the next commit to master, which I am going to make tonight.

**Comment by JordanRushing** [comment]
Awesome - I'll test on the next version. Thank you.

**Comment by ragavvenkatesan** [comment]
You can just add that one line on your local fork for it to work at the moment. Let me know if you have trouble with that still.

**Comment by JordanRushing** [comment]
Adding that import resolved the featured error - thanks!

**Comment by ragavvenkatesan** [comment]
Alright. I will make this addition in the next push. I already have it in my local clone, I am wondering why it wasn't on the git. My students in my course are using this quick start and are not claiming there are any errors with this at the moment, so I assume that they have the correct code. This is curious ... 

In any case, I will make this bug fix. Thanks. R
