### ISSUE TITLE
NameError: name 'cost' is not defined in /yann/network.py

### ISSUE THREAD

**Issue by JordanRushing** [ragavvenkatesan/yann#21]
While working through the quick-start documentation to gain more YANN knowledge for better test design I encountered an error with the function `net.test()`

I have a pull request ready to be created that will also fix misc. import issues that allow for `net.cook()` to work fully before calling `net.train()`

Below is a screenshot of the python interpreter trace and the source of the issue within network.py

![net_train_nameerror](https://cloud.githubusercontent.com/assets/3335605/23187833/f040de5e-f851-11e6-9932-9bb12db546c3.png)

**Comment by ragavvenkatesan** [comment]
This error was created on my last push. I will fix it today. Watch the dev branch.

**Comment by JordanRushing** [comment]
@ragavvenkatesan No problem - thank you very much!

**Comment by ragavvenkatesan** [comment]
This was solved some time ago. I also synced the master with the dev.
