### ISSUE TITLE
Need to redo readme and gh-pages.

### ISSUE THREAD

**Issue by ragavvenkatesan** [ragavvenkatesan/yann#4]
Priority is to have detailed instructions on
- Pr-requisites and their setup.
- How to setup the code 
- How to set up various architectures.
- How to run.

Second Priority is to come up with full dev level documentation using Sphinx.

**Comment by anewlearner** [comment]
@ragavvenkatesan 
Thanks for your work. It's still hard for me to make a fast transition from matconvnet into theano. Look forward to the detailed instructions.

**Comment by ragavvenkatesan** [comment]
@anewlearner Thank you for your appreciation. I am working on an intro book on convolutional neural network which is going to be a manual-sort of for a newer version of the Samosa toolbox. The toolbox called Yet Another Neural Network toolbox (Yann toolbox) for short will focus on CNNs explicitly with a lot of modern implementations and an even simpler and formal API. Follow this git for more information.

**Comment by ragavvenkatesan** [comment]
Temporary documentation and quick start guide hosted. Refer docs.

**Comment by ragavvenkatesan** [comment]
Done.
